{{- range $cluster_id, $cluster := .Values.clusters }}
kind: Service
apiVersion: v1
metadata:
  name: swift-health-exporter-{{$cluster_id}}
  labels:
    release: "{{$.Release.Name}}"
    os-cluster: {{$cluster_id}}
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/port: "9520"
    prometheus.io/targets: {{ .Values.alerts.prometheus | quote }}
spec:
  selector:
    component: swift-proxy-{{$cluster_id}}
  ports:
    - name: api
      port: {{$cluster.proxy_public_port}}
      targetPort: 443
    {{- if and $cluster.proxy_public_http_port $cluster.sans_http }}
    - name: api-http
      port: {{$cluster.proxy_public_http_port}}
      targetPort: 80
    {{- end}}
  externalIPs:
    - {{$cluster.proxy_public_ip}}
---
{{- end }}
